AllCops:
  TargetRubyVersion: 3.3
  ParserEngine: parser_prism
  DisplayStyleGuide: true
  Exclude:
    - 'src/**/golf*.rb'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/BlockDelimiters:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
